name: data-drift-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - pip:
    - sweetviz==2.1.3
    - seaborn==0.11.2
    - scipy==1.5.2
    - joblib==0.14.1
    - numpy==1.18.5
    - ipykernel==6.4.1
    - matplotlib==3.4.3
    - pandas==1.4.3
    - pyyaml==6.0
    - pytest==7.2.0